export const url = {
  crearBolsillo: (bolsilloId, nombre, usuarioId, porcentajeAhorro) => `crearbolsillo/${bolsilloId}/${nombre}/${usuarioId}/${porcentajeAhorro}`,
  editarBolsillo: (bolsilloId, nombre, usuarioId, porcentajeAhorro) => `actualizarBolsillo/${bolsilloId}/${nombre}/${usuarioId}/${porcentajeAhorro}`,
  crearUsuario: (usuarioId, nombre, correo) => `crearUsuario/${usuarioId}/${nombre}/${correo}`,
  buscarUsuario: (usuarioId) => `mostrarUsuario/${usuarioId}`,
  buscarBolsillos: (usuarioId) => `mostrarBolsilloUid/${usuarioId}`,
  buscarBolsillo: (bolsilloId) => `mostrarBolsillo/${bolsilloId}`,
  eliminarBolsillo: (bolsilloId) => `eliminarBolsillo/${bolsilloId}`,
  ingresarSaldo: (movimientoId, saldo, bolsilloId, usuarioId) => `ingresarDinero/${movimientoId}/${saldo}/${bolsilloId}/${usuarioId}`,
  sacarDinero: (movimientoId, saldo, bolsilloId, usuarioId) => `sacarDinero/${movimientoId}/${saldo}/${bolsilloId}/${usuarioId}`,
  ingresosMensuales: (bolsilloId, mes, año) => `ingresosMensuales/${bolsilloId}/${mes}/${año}`,
  egresosMensuales: (bolsilloId, mes, año) => `egresosMensuales/${bolsilloId}/${mes}/${año}`,
  buscarMovimientos: (bolsilloId) => `mostrarMovimientos/${bolsilloId}`,
  buscarUsuarios: `mostrarUsuarios`,
}